# Generated by Django 5.2.7 on 2026-06-02 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('date_consultation', models.DateTimeField()),
                ('motif', models.TextField()),
                ('diagnostic', models.TextField(blank=True)),
                ('traitement_prescrit', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('examens_demandes', models.TextField(blank=True)),
                ('resultats_examens', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('numero_dossier', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=10)),
                ('allergies', models.TextField(blank=True)),
                ('antecedents_medicaux', models.TextField(blank=True)),
                ('antecedents_chirurgicaux', models.TextField(blank=True)),
                ('traitements_en_cours', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_medicaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('titre', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('ordonnance', 'Ordonnance'), ('resultat_examen', "Résultat d'examen"), ('compte_rendu', 'Compte rendu'), ('imagerie', 'Imagerie médicale'), ('autre', 'Autre')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents_medicaux/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('date_document', models.DateField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='dossiers.consultation')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers.dossiermedical')),
            ],
            options={
                'ordering': ['-date_document'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dossiers.dossiermedical'),
        ),
        migrations.AddIndex(
            model_name='dossiermedical',
            index=models.Index(fields=['tenant_id', 'patient'], name='dossiers_do_tenant__cd09dc_idx'),
        ),
        migrations.AddIndex(
            model_name='dossiermedical',
            index=models.Index(fields=['numero_dossier'], name='dossiers_do_numero__e06e63_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmedical',
            index=models.Index(fields=['tenant_id', 'dossier'], name='dossiers_do_tenant__94de9f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmedical',
            index=models.Index(fields=['type_document'], name='dossiers_do_type_do_befc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['tenant_id', 'dossier'], name='dossiers_co_tenant__779ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['medecin', 'date_consultation'], name='dossiers_co_medecin_46cded_idx'),
        ),
    ]
